apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-backend
  name: shop-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
      - image: joezou-docker.pkg.coding.net/eshop/release/eshop
        name: shop-backend
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-cred